apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      # nodePort: 30080
    - name: delve
      port: 2345
      targetPort: 2345
      # nodePort: 32345
  selector:
    name: {{ template "fullname" . }}